ALTER TABLE users
ADD COLUMN public_id VARCHAR(12) UNIQUE;


UPDATE users
SET public_id = SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 12)
WHERE public_id IS NULL;


ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN public_id TO id;
ALTER TABLE users ADD PRIMARY KEY (id);

ALTER TABLE events
ALTER COLUMN owner_id TYPE VARCHAR(12);