basePath: /api/v1
definitions:
  events.EventCreateInput:
    properties:
      createdAt:
        example: "2023-11-03T10:15:30Z"
        type: string
      date:
        example: "2023-07-10"
        type: string
      description:
        example: Example Description
        type: string
      level:
        example: Any
        type: string
      location:
        example: Central Park
        type: string
      name:
        example: Basketball Match at Park
        type: string
      price:
        example: 123
        type: integer
      sport:
        example: Basketball
        type: string
    type: object
  events.EventInput:
    properties:
      date:
        example: "2023-07-10"
        type: string
      description:
        example: Example Description
        type: string
      level:
        example: Any
        type: string
      location:
        example: Central Park
        type: string
      name:
        example: Basketball Match at Park
        type: string
      price:
        example: 123
        type: integer
      sport:
        example: Basketball
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Event:
    properties:
      createdAt:
        example: "2023-11-03T10:15:30Z"
        type: string
      date:
        example: "2023-07-10"
        type: string
      description:
        example: Example Description
        type: string
      id:
        example: pwnrxtbi9z0v
        type: string
      level:
        example: Any
        type: string
      location:
        example: Central Park
        type: string
      name:
        example: Basketball Match at Park
        type: string
      price:
        example: 123
        type: integer
      sport:
        example: Basketball
        type: string
    type: object
  user.LoginInput:
    properties:
      email:
        example: email@test.com
        type: string
      password:
        example: Test123
        type: string
    required:
    - email
    - password
    type: object
  user.RegisterInput:
    properties:
      email:
        example: email@test.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: Test123
        type: string
    required:
    - email
    - name
    - password
    type: object
  user.userResponse:
    properties:
      email:
        example: email@test.com
        type: string
      id:
        example: 123
        type: integer
      name:
        example: John Doe
        type: string
      rating:
        example: 3
        type: integer
    type: object
host: sportujspolu-api.onrender.com
info:
  contact: {}
  description: This is the API for the SportujSpolu app.
  title: SportujSpolu API
  version: "1.0"
paths:
  /events:
    get:
      description: Retrieve all events from the database
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of events per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all events
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Creates a new event in the database
      parameters:
      - description: Event object
        in: body
        name: newEvent
        required: true
        schema:
          $ref: '#/definitions/events.EventCreateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new event
      tags:
      - events
  /events/{eventId}:
    delete:
      description: Delete an existing event with the given event ID
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete an event
      tags:
      - events
    get:
      description: Retrieves a single event from the database
      parameters:
      - description: Event ID
        example: '"q76j5d1a3xtn"'
        in: path
        name: eventId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a single event
      tags:
      - events
    put:
      consumes:
      - application/json
      description: Update an existing event with the given event ID
      parameters:
      - description: Event ID
        in: path
        name: eventId
        required: true
        type: integer
      - description: Event object that needs to be updated
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/events.EventInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update an event
      tags:
      - events
  /user/login:
    post:
      consumes:
      - application/json
      description: Logs in a user with the provided credentials
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: User login
      tags:
      - user
  /user/me:
    get:
      description: Gets the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.userResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided details
      parameters:
      - description: Registration details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Register a new user
      tags:
      - user
schemes:
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
